# Generated by Django 2.2 on 2019-04-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_data',
            new_name='dimemployees',
        ),
    ]
